local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("☠️GlobalWave Official | [BridgeWorm]-[GUI]☠️", "GrapeTheme")
local Tab = Window:NewTab("☠️GLOBAL☠️")
local Section = Tab:NewSection("Global")
Section:NewDropdown("🔔REMEMBER🔔", "Hope You Will Understand ...", {"Dont Abuse !!!", "Dont Permrank Anyone For NoReason !!!", "Dont Bring All !!!", "Dont Kill All !!!", "ThankYou !!!"}, function(currentOption)
    print(currentOption)
end)
Section:NewKeybind("Open / Close", "O_O", Enum.KeyCode.E, function()
	Library:ToggleUI()
end)
local Tab = Window:NewTab("☠️Bridge-Worm☠️")
local Section = Tab:NewSection("☠️| Bridge Worm |☠️")
Section:NewButton("👉PROCEED👈", "Enjoy !!!", function()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-17014, 71, -1186)
wait()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1657, 114, -1317)
end)
